# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastro.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class TelaCadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(93, 93, 93);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(450, 550))
        self.frame_4.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(5, 50, 441, 37))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.campo_NumeroConta = QtWidgets.QLineEdit(self.frame_4)
        self.campo_NumeroConta.setGeometry(QtCore.QRect(170, 330, 251, 34))
        self.campo_NumeroConta.setMaximumSize(QtCore.QSize(300, 16777215))
        self.campo_NumeroConta.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.campo_NumeroConta.setText("")
        self.campo_NumeroConta.setObjectName("campo_NumeroConta")
        self.campo_Sobrenome = QtWidgets.QLineEdit(self.frame_4)
        self.campo_Sobrenome.setGeometry(QtCore.QRect(170, 210, 251, 34))
        self.campo_Sobrenome.setMaximumSize(QtCore.QSize(300, 16777215))
        self.campo_Sobrenome.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.campo_Sobrenome.setText("")
        self.campo_Sobrenome.setObjectName("campo_Sobrenome")
        self.campo_cpf = QtWidgets.QLineEdit(self.frame_4)
        self.campo_cpf.setGeometry(QtCore.QRect(170, 270, 251, 34))
        self.campo_cpf.setMaximumSize(QtCore.QSize(300, 16777215))
        self.campo_cpf.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.campo_cpf.setText("")
        self.campo_cpf.setObjectName("campo_cpf")
        self.campo_nome = QtWidgets.QLineEdit(self.frame_4)
        self.campo_nome.setGeometry(QtCore.QRect(170, 150, 251, 34))
        self.campo_nome.setMaximumSize(QtCore.QSize(300, 16777215))
        self.campo_nome.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.campo_nome.setText("")
        self.campo_nome.setObjectName("campo_nome")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 67, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 81, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(30, 270, 67, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 121, 22))
        self.label_5.setObjectName("label_5")
        self.botao_voltar = QtWidgets.QPushButton(self.frame_4)
        self.botao_voltar.setGeometry(QtCore.QRect(70, 440, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.botao_voltar.setFont(font)
        self.botao_voltar.setObjectName("botao_voltar")
        self.botao_salvar = QtWidgets.QPushButton(self.frame_4)
        self.botao_salvar.setGeometry(QtCore.QRect(240, 440, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.botao_salvar.setFont(font)
        self.botao_salvar.setObjectName("botao_salvar")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Cadastro</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.label_3.setText(_translate("MainWindow", "Sobrenome"))
        self.label_4.setText(_translate("MainWindow", "CPF"))
        self.label_5.setText(_translate("MainWindow", "Número da contaonta"))
        self.botao_voltar.setText(_translate("MainWindow", "Voltar"))
        self.botao_salvar.setText(_translate("MainWindow", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaCadastro()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

